//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALE_MexJet.wsSyteline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ws_SyteLine")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaPaso1", Namespace="http://schemas.datacontract.org/2004/07/ws_SyteLine.Objetos")]
    [System.SerializableAttribute()]
    public partial class FacturaPaso1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DtFechaRegresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DtFechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfMarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfremisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfrutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfserieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dExch_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dSales_taxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtInvDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFacturanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sInvNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMetodoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTax_code1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsoCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DtFechaRegreso {
            get {
                return this.DtFechaRegresoField;
            }
            set {
                if ((this.DtFechaRegresoField.Equals(value) != true)) {
                    this.DtFechaRegresoField = value;
                    this.RaisePropertyChanged("DtFechaRegreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DtFechaSalida {
            get {
                return this.DtFechaSalidaField;
            }
            set {
                if ((this.DtFechaSalidaField.Equals(value) != true)) {
                    this.DtFechaSalidaField = value;
                    this.RaisePropertyChanged("DtFechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoFactura {
            get {
                return this.TipoFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoFacturaField, value) != true)) {
                    this.TipoFacturaField = value;
                    this.RaisePropertyChanged("TipoFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UfMarca {
            get {
                return this.UfMarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.UfMarcaField, value) != true)) {
                    this.UfMarcaField = value;
                    this.RaisePropertyChanged("UfMarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UfModelo {
            get {
                return this.UfModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.UfModeloField, value) != true)) {
                    this.UfModeloField = value;
                    this.RaisePropertyChanged("UfModelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ufremision {
            get {
                return this.UfremisionField;
            }
            set {
                if ((object.ReferenceEquals(this.UfremisionField, value) != true)) {
                    this.UfremisionField = value;
                    this.RaisePropertyChanged("Ufremision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ufruta {
            get {
                return this.UfrutaField;
            }
            set {
                if ((object.ReferenceEquals(this.UfrutaField, value) != true)) {
                    this.UfrutaField = value;
                    this.RaisePropertyChanged("Ufruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ufserie {
            get {
                return this.UfserieField;
            }
            set {
                if ((object.ReferenceEquals(this.UfserieField, value) != true)) {
                    this.UfserieField = value;
                    this.RaisePropertyChanged("Ufserie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dAmount {
            get {
                return this.dAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.dAmountField, value) != true)) {
                    this.dAmountField = value;
                    this.RaisePropertyChanged("dAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dExch_rate {
            get {
                return this.dExch_rateField;
            }
            set {
                if ((object.ReferenceEquals(this.dExch_rateField, value) != true)) {
                    this.dExch_rateField = value;
                    this.RaisePropertyChanged("dExch_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dSales_tax {
            get {
                return this.dSales_taxField;
            }
            set {
                if ((object.ReferenceEquals(this.dSales_taxField, value) != true)) {
                    this.dSales_taxField = value;
                    this.RaisePropertyChanged("dSales_tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtDueDate {
            get {
                return this.dtDueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.dtDueDateField, value) != true)) {
                    this.dtDueDateField = value;
                    this.RaisePropertyChanged("dtDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtInvDate {
            get {
                return this.dtInvDateField;
            }
            set {
                if ((object.ReferenceEquals(this.dtInvDateField, value) != true)) {
                    this.dtInvDateField = value;
                    this.RaisePropertyChanged("dtInvDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iEmpresa {
            get {
                return this.iEmpresaField;
            }
            set {
                if ((this.iEmpresaField.Equals(value) != true)) {
                    this.iEmpresaField = value;
                    this.RaisePropertyChanged("iEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct {
            get {
                return this.sAcctField;
            }
            set {
                if ((object.ReferenceEquals(this.sAcctField, value) != true)) {
                    this.sAcctField = value;
                    this.RaisePropertyChanged("sAcct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit3 {
            get {
                return this.sAcct_unit3Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit3Field, value) != true)) {
                    this.sAcct_unit3Field = value;
                    this.RaisePropertyChanged("sAcct_unit3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit4 {
            get {
                return this.sAcct_unit4Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit4Field, value) != true)) {
                    this.sAcct_unit4Field = value;
                    this.RaisePropertyChanged("sAcct_unit4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescription {
            get {
                return this.sDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescriptionField, value) != true)) {
                    this.sDescriptionField = value;
                    this.RaisePropertyChanged("sDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFacturante {
            get {
                return this.sFacturanteField;
            }
            set {
                if ((object.ReferenceEquals(this.sFacturanteField, value) != true)) {
                    this.sFacturanteField = value;
                    this.RaisePropertyChanged("sFacturante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFormaPago {
            get {
                return this.sFormaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.sFormaPagoField, value) != true)) {
                    this.sFormaPagoField = value;
                    this.RaisePropertyChanged("sFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sInvNum {
            get {
                return this.sInvNumField;
            }
            set {
                if ((object.ReferenceEquals(this.sInvNumField, value) != true)) {
                    this.sInvNumField = value;
                    this.RaisePropertyChanged("sInvNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMetodoPago {
            get {
                return this.sMetodoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.sMetodoPagoField, value) != true)) {
                    this.sMetodoPagoField = value;
                    this.RaisePropertyChanged("sMetodoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMoneda {
            get {
                return this.sMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.sMonedaField, value) != true)) {
                    this.sMonedaField = value;
                    this.RaisePropertyChanged("sMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sRef {
            get {
                return this.sRefField;
            }
            set {
                if ((object.ReferenceEquals(this.sRefField, value) != true)) {
                    this.sRefField = value;
                    this.RaisePropertyChanged("sRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSerie {
            get {
                return this.sSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.sSerieField, value) != true)) {
                    this.sSerieField = value;
                    this.RaisePropertyChanged("sSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSucursal {
            get {
                return this.sSucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.sSucursalField, value) != true)) {
                    this.sSucursalField = value;
                    this.RaisePropertyChanged("sSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTax_code1 {
            get {
                return this.sTax_code1Field;
            }
            set {
                if ((object.ReferenceEquals(this.sTax_code1Field, value) != true)) {
                    this.sTax_code1Field = value;
                    this.RaisePropertyChanged("sTax_code1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipo {
            get {
                return this.sTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.sTipoField, value) != true)) {
                    this.sTipoField = value;
                    this.RaisePropertyChanged("sTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsoCFDI {
            get {
                return this.sUsoCFDIField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsoCFDIField, value) != true)) {
                    this.sUsoCFDIField = value;
                    this.RaisePropertyChanged("sUsoCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsuario {
            get {
                return this.sUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsuarioField, value) != true)) {
                    this.sUsuarioField = value;
                    this.RaisePropertyChanged("sUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaPaso2", Namespace="http://schemas.datacontract.org/2004/07/ws_SyteLine.Objetos")]
    [System.SerializableAttribute()]
    public partial class FacturaPaso2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal dDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iDistSeqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iTaxSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAcct_unit5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoBarrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sConceptoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFacturanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sInvNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTax_code1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dAmount {
            get {
                return this.dAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.dAmountField, value) != true)) {
                    this.dAmountField = value;
                    this.RaisePropertyChanged("dAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dDescuento {
            get {
                return this.dDescuentoField;
            }
            set {
                if ((this.dDescuentoField.Equals(value) != true)) {
                    this.dDescuentoField = value;
                    this.RaisePropertyChanged("dDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCantidad {
            get {
                return this.iCantidadField;
            }
            set {
                if ((this.iCantidadField.Equals(value) != true)) {
                    this.iCantidadField = value;
                    this.RaisePropertyChanged("iCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iDistSeq {
            get {
                return this.iDistSeqField;
            }
            set {
                if ((object.ReferenceEquals(this.iDistSeqField, value) != true)) {
                    this.iDistSeqField = value;
                    this.RaisePropertyChanged("iDistSeq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iEmpresa {
            get {
                return this.iEmpresaField;
            }
            set {
                if ((this.iEmpresaField.Equals(value) != true)) {
                    this.iEmpresaField = value;
                    this.RaisePropertyChanged("iEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdFactura {
            get {
                return this.iIdFacturaField;
            }
            set {
                if ((this.iIdFacturaField.Equals(value) != true)) {
                    this.iIdFacturaField = value;
                    this.RaisePropertyChanged("iIdFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iTaxSystem {
            get {
                return this.iTaxSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.iTaxSystemField, value) != true)) {
                    this.iTaxSystemField = value;
                    this.RaisePropertyChanged("iTaxSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct {
            get {
                return this.sAcctField;
            }
            set {
                if ((object.ReferenceEquals(this.sAcctField, value) != true)) {
                    this.sAcctField = value;
                    this.RaisePropertyChanged("sAcct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit1 {
            get {
                return this.sAcct_unit1Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit1Field, value) != true)) {
                    this.sAcct_unit1Field = value;
                    this.RaisePropertyChanged("sAcct_unit1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit2 {
            get {
                return this.sAcct_unit2Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit2Field, value) != true)) {
                    this.sAcct_unit2Field = value;
                    this.RaisePropertyChanged("sAcct_unit2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit3 {
            get {
                return this.sAcct_unit3Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit3Field, value) != true)) {
                    this.sAcct_unit3Field = value;
                    this.RaisePropertyChanged("sAcct_unit3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit4 {
            get {
                return this.sAcct_unit4Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit4Field, value) != true)) {
                    this.sAcct_unit4Field = value;
                    this.RaisePropertyChanged("sAcct_unit4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAcct_unit5 {
            get {
                return this.sAcct_unit5Field;
            }
            set {
                if ((object.ReferenceEquals(this.sAcct_unit5Field, value) != true)) {
                    this.sAcct_unit5Field = value;
                    this.RaisePropertyChanged("sAcct_unit5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAlmacen {
            get {
                return this.sAlmacenField;
            }
            set {
                if ((object.ReferenceEquals(this.sAlmacenField, value) != true)) {
                    this.sAlmacenField = value;
                    this.RaisePropertyChanged("sAlmacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoBarras {
            get {
                return this.sCodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.sCodigoBarrasField, value) != true)) {
                    this.sCodigoBarrasField = value;
                    this.RaisePropertyChanged("sCodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sConceptoUsuario {
            get {
                return this.sConceptoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sConceptoUsuarioField, value) != true)) {
                    this.sConceptoUsuarioField = value;
                    this.RaisePropertyChanged("sConceptoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFacturante {
            get {
                return this.sFacturanteField;
            }
            set {
                if ((object.ReferenceEquals(this.sFacturanteField, value) != true)) {
                    this.sFacturanteField = value;
                    this.RaisePropertyChanged("sFacturante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sInvNum {
            get {
                return this.sInvNumField;
            }
            set {
                if ((object.ReferenceEquals(this.sInvNumField, value) != true)) {
                    this.sInvNumField = value;
                    this.RaisePropertyChanged("sInvNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sItem {
            get {
                return this.sItemField;
            }
            set {
                if ((object.ReferenceEquals(this.sItemField, value) != true)) {
                    this.sItemField = value;
                    this.RaisePropertyChanged("sItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sProyecto {
            get {
                return this.sProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.sProyectoField, value) != true)) {
                    this.sProyectoField = value;
                    this.RaisePropertyChanged("sProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTax_code1 {
            get {
                return this.sTax_code1Field;
            }
            set {
                if ((object.ReferenceEquals(this.sTax_code1Field, value) != true)) {
                    this.sTax_code1Field = value;
                    this.RaisePropertyChanged("sTax_code1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsuario {
            get {
                return this.sUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsuarioField, value) != true)) {
                    this.sUsuarioField = value;
                    this.RaisePropertyChanged("sUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaPaso3", Namespace="http://schemas.datacontract.org/2004/07/ws_SyteLine.Objetos")]
    [System.SerializableAttribute()]
    public partial class FacturaPaso3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteExistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iIsWorkflowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sInvNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sdescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoteExist {
            get {
                return this.NoteExistField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteExistField, value) != true)) {
                    this.NoteExistField = value;
                    this.RaisePropertyChanged("NoteExist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dPrice {
            get {
                return this.dPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.dPriceField, value) != true)) {
                    this.dPriceField = value;
                    this.RaisePropertyChanged("dPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dQty {
            get {
                return this.dQtyField;
            }
            set {
                if ((object.ReferenceEquals(this.dQtyField, value) != true)) {
                    this.dQtyField = value;
                    this.RaisePropertyChanged("dQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iIsWorkflow {
            get {
                return this.iIsWorkflowField;
            }
            set {
                if ((object.ReferenceEquals(this.iIsWorkflowField, value) != true)) {
                    this.iIsWorkflowField = value;
                    this.RaisePropertyChanged("iIsWorkflow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iLine {
            get {
                return this.iLineField;
            }
            set {
                if ((object.ReferenceEquals(this.iLineField, value) != true)) {
                    this.iLineField = value;
                    this.RaisePropertyChanged("iLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sInvNum {
            get {
                return this.sInvNumField;
            }
            set {
                if ((object.ReferenceEquals(this.sInvNumField, value) != true)) {
                    this.sInvNumField = value;
                    this.RaisePropertyChanged("sInvNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUM {
            get {
                return this.sUMField;
            }
            set {
                if ((object.ReferenceEquals(this.sUMField, value) != true)) {
                    this.sUMField = value;
                    this.RaisePropertyChanged("sUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsuario {
            get {
                return this.sUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsuarioField, value) != true)) {
                    this.sUsuarioField = value;
                    this.RaisePropertyChanged("sUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sdescription {
            get {
                return this.sdescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.sdescriptionField, value) != true)) {
                    this.sdescriptionField = value;
                    this.RaisePropertyChanged("sdescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSyteline.Iws_SyteLine")]
    public interface Iws_SyteLine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetData", ReplyAction="http://tempuri.org/Iws_SyteLine/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetData", ReplyAction="http://tempuri.org/Iws_SyteLine/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCodigoUnidad_Uno_Vendedor", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCodigoUnidad_Uno_VendedorResponse")]
        System.Data.DataSet GetCodigoUnidad_Uno_Vendedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCodigoUnidad_Uno_Vendedor", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCodigoUnidad_Uno_VendedorResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCodigoUnidad_Uno_VendedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCuentasContables", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCuentasContablesResponse")]
        System.Data.DataSet GetCuentasContables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCuentasContables", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCuentasContablesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCuentasContablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCuentasContablesServicios", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCuentasContablesServiciosResponse")]
        System.Data.DataSet GetCuentasContablesServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetCuentasContablesServicios", ReplyAction="http://tempuri.org/Iws_SyteLine/GetCuentasContablesServiciosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCuentasContablesServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetFacturantes", ReplyAction="http://tempuri.org/Iws_SyteLine/GetFacturantesResponse")]
        System.Data.DataSet GetFacturantes(string sTipo, string sContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetFacturantes", ReplyAction="http://tempuri.org/Iws_SyteLine/GetFacturantesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFacturantesAsync(string sTipo, string sContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ValidaFacturante", ReplyAction="http://tempuri.org/Iws_SyteLine/ValidaFacturanteResponse")]
        string ValidaFacturante(string sFacturante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ValidaFacturante", ReplyAction="http://tempuri.org/Iws_SyteLine/ValidaFacturanteResponse")]
        System.Threading.Tasks.Task<string> ValidaFacturanteAsync(string sFacturante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetNumFactura", ReplyAction="http://tempuri.org/Iws_SyteLine/GetNumFacturaResponse")]
        string GetNumFactura(string sFacturante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetNumFactura", ReplyAction="http://tempuri.org/Iws_SyteLine/GetNumFacturaResponse")]
        System.Threading.Tasks.Task<string> GetNumFacturaAsync(string sFacturante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetDataUsingDataContract", ReplyAction="http://tempuri.org/Iws_SyteLine/GetDataUsingDataContractResponse")]
        ALE_MexJet.wsSyteline.CompositeType GetDataUsingDataContract(ALE_MexJet.wsSyteline.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetDataUsingDataContract", ReplyAction="http://tempuri.org/Iws_SyteLine/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ALE_MexJet.wsSyteline.CompositeType> GetDataUsingDataContractAsync(ALE_MexJet.wsSyteline.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveArinV", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveArinVResponse")]
        string SaveArinV(ALE_MexJet.wsSyteline.FacturaPaso1 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveArinV", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveArinVResponse")]
        System.Threading.Tasks.Task<string> SaveArinVAsync(ALE_MexJet.wsSyteline.FacturaPaso1 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveArinVD", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveArinVDResponse")]
        string SaveArinVD(ALE_MexJet.wsSyteline.FacturaPaso2 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveArinVD", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveArinVDResponse")]
        System.Threading.Tasks.Task<string> SaveArinVDAsync(ALE_MexJet.wsSyteline.FacturaPaso2 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveConceptoFacFinanciera", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveConceptoFacFinancieraResponse")]
        string SaveConceptoFacFinanciera(ALE_MexJet.wsSyteline.FacturaPaso3 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SaveConceptoFacFinanciera", ReplyAction="http://tempuri.org/Iws_SyteLine/SaveConceptoFacFinancieraResponse")]
        System.Threading.Tasks.Task<string> SaveConceptoFacFinancieraAsync(ALE_MexJet.wsSyteline.FacturaPaso3 Paso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionMXNResponse")]
        System.Data.DataSet GetEstadoCuentaFacturacionMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionMXNResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaFacturacionMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionDLLSResponse")]
        System.Data.DataSet GetEstadoCuentaFacturacionDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaFacturacionDLLSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaFacturacionDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoDLLSResponse")]
        System.Data.DataSet GetEstadoCuentaResumenNoAcumuladoDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoDLLSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenNoAcumuladoDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoMXNResponse")]
        System.Data.DataSet GetEstadoCuentaResumenNoAcumuladoMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenNoAcumuladoMXNResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenNoAcumuladoMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoDLLSResponse")]
        System.Data.DataSet GetEstadoCuentaResumenAcumuladoDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoDLLS", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoDLLSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenAcumuladoDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoMXNResponse")]
        System.Data.DataSet GetEstadoCuentaResumenAcumuladoMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoMXN", ReplyAction="http://tempuri.org/Iws_SyteLine/GetEstadoCuentaResumenAcumuladoMXNResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenAcumuladoMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ValidaEstatusCancelacionFactura", ReplyAction="http://tempuri.org/Iws_SyteLine/ValidaEstatusCancelacionFacturaResponse")]
        string ValidaEstatusCancelacionFactura(string sNumFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ValidaEstatusCancelacionFactura", ReplyAction="http://tempuri.org/Iws_SyteLine/ValidaEstatusCancelacionFacturaResponse")]
        System.Threading.Tasks.Task<string> ValidaEstatusCancelacionFacturaAsync(string sNumFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetMovimientosAnterioresEdoCuenta", ReplyAction="http://tempuri.org/Iws_SyteLine/GetMovimientosAnterioresEdoCuentaResponse")]
        System.Data.DataSet GetMovimientosAnterioresEdoCuenta(string sClaveCliente, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetMovimientosAnterioresEdoCuenta", ReplyAction="http://tempuri.org/Iws_SyteLine/GetMovimientosAnterioresEdoCuentaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMovimientosAnterioresEdoCuentaAsync(string sClaveCliente, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambio", ReplyAction="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioResponse")]
        string RecuperaTipoCambio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambio", ReplyAction="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioResponse")]
        System.Threading.Tasks.Task<string> RecuperaTipoCambioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioFecha", ReplyAction="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioFechaResponse")]
        string RecuperaTipoCambioFecha(System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioFecha", ReplyAction="http://tempuri.org/Iws_SyteLine/RecuperaTipoCambioFechaResponse")]
        System.Threading.Tasks.Task<string> RecuperaTipoCambioFechaAsync(System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetFacturasTabulado", ReplyAction="http://tempuri.org/Iws_SyteLine/GetFacturasTabuladoResponse")]
        string GetFacturasTabulado(string sTiposFactura, System.DateTime dtFechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetFacturasTabulado", ReplyAction="http://tempuri.org/Iws_SyteLine/GetFacturasTabuladoResponse")]
        System.Threading.Tasks.Task<string> GetFacturasTabuladoAsync(string sTiposFactura, System.DateTime dtFechaInicio, System.DateTime dtFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GeneraSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/GeneraSolicitudVueloResponse")]
        string GeneraSolicitudVuelo(string sClaveContrato, string sNombreContacto, string sCorreoContacto, int iIdMotivo, int iOrigen, string sMatricula, int iIdTipoEquipo, string sNotasVuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GeneraSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/GeneraSolicitudVueloResponse")]
        System.Threading.Tasks.Task<string> GeneraSolicitudVueloAsync(string sClaveContrato, string sNombreContacto, string sCorreoContacto, int iIdMotivo, int iOrigen, string sMatricula, int iIdTipoEquipo, string sNotasVuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GeneraPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/GeneraPiernasResponse")]
        string GeneraPiernas(int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GeneraPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/GeneraPiernasResponse")]
        System.Threading.Tasks.Task<string> GeneraPiernasAsync(int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/CancelaSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/CancelaSolicitudVueloResponse")]
        string CancelaSolicitudVuelo(int iIdSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/CancelaSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/CancelaSolicitudVueloResponse")]
        System.Threading.Tasks.Task<string> CancelaSolicitudVueloAsync(int iIdSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaSolicitudVueloResponse")]
        string ConsultaSolicitudVuelo(int iIdSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaSolicitudVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaSolicitudVueloResponse")]
        System.Threading.Tasks.Task<string> ConsultaSolicitudVueloAsync(int iIdSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/EliminaPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/EliminaPiernasResponse")]
        string EliminaPiernas(int iIdTramo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/EliminaPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/EliminaPiernasResponse")]
        System.Threading.Tasks.Task<string> EliminaPiernasAsync(int iIdTramo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ActualizaPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/ActualizaPiernasResponse")]
        string ActualizaPiernas(int iIdTramo, int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ActualizaPiernas", ReplyAction="http://tempuri.org/Iws_SyteLine/ActualizaPiernasResponse")]
        System.Threading.Tasks.Task<string> ActualizaPiernasAsync(int iIdTramo, int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ActualizaSolicitud", ReplyAction="http://tempuri.org/Iws_SyteLine/ActualizaSolicitudResponse")]
        string ActualizaSolicitud(int iIdSolicitud, int iIdTipoEquipo, string sNotasVuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ActualizaSolicitud", ReplyAction="http://tempuri.org/Iws_SyteLine/ActualizaSolicitudResponse")]
        System.Threading.Tasks.Task<string> ActualizaSolicitudAsync(int iIdSolicitud, int iIdTipoEquipo, string sNotasVuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaPreferenciasClienteAPP", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaPreferenciasClienteAPPResponse")]
        string ConsultaPreferenciasClienteAPP(string sClaveContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaPreferenciasClienteAPP", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaPreferenciasClienteAPPResponse")]
        System.Threading.Tasks.Task<string> ConsultaPreferenciasClienteAPPAsync(string sClaveContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaCasosClienteAPP", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaCasosClienteAPPResponse")]
        string ConsultaCasosClienteAPP(string sClaveContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaCasosClienteAPP", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaCasosClienteAPPResponse")]
        System.Threading.Tasks.Task<string> ConsultaCasosClienteAPPAsync(string sClaveContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetInformacionFlightPak", ReplyAction="http://tempuri.org/Iws_SyteLine/GetInformacionFlightPakResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ALE_MexJet.wsSyteline.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ALE_MexJet.wsSyteline.FacturaPaso1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ALE_MexJet.wsSyteline.FacturaPaso2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ALE_MexJet.wsSyteline.FacturaPaso3))]
        System.Data.DataSet GetInformacionFlightPak(string sQuery, object[] oArrFiltros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetInformacionFlightPak", ReplyAction="http://tempuri.org/Iws_SyteLine/GetInformacionFlightPakResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetInformacionFlightPakAsync(string sQuery, object[] oArrFiltros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetInformacionVuelosFerrys", ReplyAction="http://tempuri.org/Iws_SyteLine/GetInformacionVuelosFerrysResponse")]
        string GetInformacionVuelosFerrys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetInformacionVuelosFerrys", ReplyAction="http://tempuri.org/Iws_SyteLine/GetInformacionVuelosFerrysResponse")]
        System.Threading.Tasks.Task<string> GetInformacionVuelosFerrysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetCambiaEstatusFerry", ReplyAction="http://tempuri.org/Iws_SyteLine/SetCambiaEstatusFerryResponse")]
        string SetCambiaEstatusFerry(string sCadJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetCambiaEstatusFerry", ReplyAction="http://tempuri.org/Iws_SyteLine/SetCambiaEstatusFerryResponse")]
        System.Threading.Tasks.Task<string> SetCambiaEstatusFerryAsync(string sCadJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetProcesaJSON", ReplyAction="http://tempuri.org/Iws_SyteLine/SetProcesaJSONResponse")]
        string SetProcesaJSON(string sCad, int iOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetProcesaJSON", ReplyAction="http://tempuri.org/Iws_SyteLine/SetProcesaJSONResponse")]
        System.Threading.Tasks.Task<string> SetProcesaJSONAsync(string sCad, int iOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtienePromedioVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtienePromedioVueloResponse")]
        string ObtienePromedioVuelo(int iIdGrupoModelo, string sOrigenICAO, string sDestinoICAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtienePromedioVuelo", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtienePromedioVueloResponse")]
        System.Threading.Tasks.Task<string> ObtienePromedioVueloAsync(int iIdGrupoModelo, string sOrigenICAO, string sDestinoICAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDatosPilotoPorClave", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDatosPilotoPorClaveResponse")]
        System.Data.DataSet ObtieneDatosPilotoPorClave(string sClave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDatosPilotoPorClave", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDatosPilotoPorClaveResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtieneDatosPilotoPorClaveAsync(string sClave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstatusPiloto", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstatusPilotoResponse")]
        string ObtieneEstatusPiloto(string sCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstatusPiloto", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstatusPilotoResponse")]
        System.Threading.Tasks.Task<string> ObtieneEstatusPilotoAsync(string sCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorPiloto", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorPilotoResponse")]
        string ObtieneVuelosPorPiloto(string sClavePiloto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorPiloto", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorPilotoResponse")]
        System.Threading.Tasks.Task<string> ObtieneVuelosPorPilotoAsync(string sClavePiloto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorRangoDeFechas", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorRangoDeFechasResponse")]
        string ObtieneVuelosPorRangoDeFechas(string sFechaInicio, string sFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorRangoDeFechas", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosPorRangoDeFechasResponse")]
        System.Threading.Tasks.Task<string> ObtieneVuelosPorRangoDeFechasAsync(string sFechaInicio, string sFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaCuentaConceptoII", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaCuentaConceptoIIResponse")]
        System.Data.DataSet ConsultaCuentaConceptoII(string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaCuentaConceptoII", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaCuentaConceptoIIResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultaCuentaConceptoIIAsync(string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaPais", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaPaisResponse")]
        System.Data.DataSet ConsultaPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaPais", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaPaisResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultaPaisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaEstadoPorPais", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaEstadoPorPaisResponse")]
        System.Data.DataSet ConsultaEstadoPorPais(int iIdPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ConsultaEstadoPorPais", ReplyAction="http://tempuri.org/Iws_SyteLine/ConsultaEstadoPorPaisResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultaEstadoPorPaisAsync(int iIdPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetPreguntasEncuesta", ReplyAction="http://tempuri.org/Iws_SyteLine/GetPreguntasEncuestaResponse")]
        string GetPreguntasEncuesta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/GetPreguntasEncuesta", ReplyAction="http://tempuri.org/Iws_SyteLine/GetPreguntasEncuestaResponse")]
        System.Threading.Tasks.Task<string> GetPreguntasEncuestaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetRecibeLlamadaConmutador", ReplyAction="http://tempuri.org/Iws_SyteLine/SetRecibeLlamadaConmutadorResponse")]
        string SetRecibeLlamadaConmutador(string sCadJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/SetRecibeLlamadaConmutador", ReplyAction="http://tempuri.org/Iws_SyteLine/SetRecibeLlamadaConmutadorResponse")]
        System.Threading.Tasks.Task<string> SetRecibeLlamadaConmutadorAsync(string sCadJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstatusUsuarioCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstatusUsuarioCMResponse")]
        string ObtieneEstatusUsuarioCM(string sCorreo, string sPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstatusUsuarioCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstatusUsuarioCMResponse")]
        System.Threading.Tasks.Task<string> ObtieneEstatusUsuarioCMAsync(string sCorreo, string sPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneMatriculasPorUsuarioCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneMatriculasPorUsuarioCMResponse")]
        string ObtieneMatriculasPorUsuarioCM(string sCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneMatriculasPorUsuarioCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneMatriculasPorUsuarioCMResponse")]
        System.Threading.Tasks.Task<string> ObtieneMatriculasPorUsuarioCMAsync(string sCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneWOporMatriculaCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneWOporMatriculaCMResponse")]
        string ObtieneWOporMatriculaCM(string sKeyMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneWOporMatriculaCM", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneWOporMatriculaCMResponse")]
        System.Threading.Tasks.Task<string> ObtieneWOporMatriculaCMAsync(string sKeyMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDetalleWO", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDetalleWOResponse")]
        string ObtieneDetalleWO(string sKeyWO, string sBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDetalleWO", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDetalleWOResponse")]
        System.Threading.Tasks.Task<string> ObtieneDetalleWOAsync(string sKeyWO, string sBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneListadoCotizaciones", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneListadoCotizacionesResponse")]
        string ObtieneListadoCotizaciones(string sKeyMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneListadoCotizaciones", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneListadoCotizacionesResponse")]
        System.Threading.Tasks.Task<string> ObtieneListadoCotizacionesAsync(string sKeyMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDetalleCotizaciones", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDetalleCotizacionesResponse")]
        string ObtieneDetalleCotizaciones(string sKeyWOQ, string sNumeroWO, string sBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneDetalleCotizaciones", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneDetalleCotizacionesResponse")]
        System.Threading.Tasks.Task<string> ObtieneDetalleCotizacionesAsync(string sKeyWOQ, string sNumeroWO, string sBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosSabanaRangoDeFechas", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosSabanaRangoDeFechasResponse")]
        string ObtieneVuelosSabanaRangoDeFechas(string sFechaInicio, string sFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneVuelosSabanaRangoDeFechas", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneVuelosSabanaRangoDeFechasResponse")]
        System.Threading.Tasks.Task<string> ObtieneVuelosSabanaRangoDeFechasAsync(string sFechaInicio, string sFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstadoDeCuentaCorridor", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstadoDeCuentaCorridorResponse")]
        string ObtieneEstadoDeCuentaCorridor(string sIdCompania, string sRFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/ObtieneEstadoDeCuentaCorridor", ReplyAction="http://tempuri.org/Iws_SyteLine/ObtieneEstadoDeCuentaCorridorResponse")]
        System.Threading.Tasks.Task<string> ObtieneEstadoDeCuentaCorridorAsync(string sIdCompania, string sRFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/EnviaCorreoWorkOrdersCM", ReplyAction="http://tempuri.org/Iws_SyteLine/EnviaCorreoWorkOrdersCMResponse")]
        string EnviaCorreoWorkOrdersCM(string sJSON);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iws_SyteLine/EnviaCorreoWorkOrdersCM", ReplyAction="http://tempuri.org/Iws_SyteLine/EnviaCorreoWorkOrdersCMResponse")]
        System.Threading.Tasks.Task<string> EnviaCorreoWorkOrdersCMAsync(string sJSON);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iws_SyteLineChannel : ALE_MexJet.wsSyteline.Iws_SyteLine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iws_SyteLineClient : System.ServiceModel.ClientBase<ALE_MexJet.wsSyteline.Iws_SyteLine>, ALE_MexJet.wsSyteline.Iws_SyteLine {
        
        public Iws_SyteLineClient() {
        }
        
        public Iws_SyteLineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iws_SyteLineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iws_SyteLineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iws_SyteLineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Data.DataSet GetCodigoUnidad_Uno_Vendedor() {
            return base.Channel.GetCodigoUnidad_Uno_Vendedor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCodigoUnidad_Uno_VendedorAsync() {
            return base.Channel.GetCodigoUnidad_Uno_VendedorAsync();
        }
        
        public System.Data.DataSet GetCuentasContables() {
            return base.Channel.GetCuentasContables();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCuentasContablesAsync() {
            return base.Channel.GetCuentasContablesAsync();
        }
        
        public System.Data.DataSet GetCuentasContablesServicios() {
            return base.Channel.GetCuentasContablesServicios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCuentasContablesServiciosAsync() {
            return base.Channel.GetCuentasContablesServiciosAsync();
        }
        
        public System.Data.DataSet GetFacturantes(string sTipo, string sContrato) {
            return base.Channel.GetFacturantes(sTipo, sContrato);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFacturantesAsync(string sTipo, string sContrato) {
            return base.Channel.GetFacturantesAsync(sTipo, sContrato);
        }
        
        public string ValidaFacturante(string sFacturante) {
            return base.Channel.ValidaFacturante(sFacturante);
        }
        
        public System.Threading.Tasks.Task<string> ValidaFacturanteAsync(string sFacturante) {
            return base.Channel.ValidaFacturanteAsync(sFacturante);
        }
        
        public string GetNumFactura(string sFacturante) {
            return base.Channel.GetNumFactura(sFacturante);
        }
        
        public System.Threading.Tasks.Task<string> GetNumFacturaAsync(string sFacturante) {
            return base.Channel.GetNumFacturaAsync(sFacturante);
        }
        
        public ALE_MexJet.wsSyteline.CompositeType GetDataUsingDataContract(ALE_MexJet.wsSyteline.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ALE_MexJet.wsSyteline.CompositeType> GetDataUsingDataContractAsync(ALE_MexJet.wsSyteline.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string SaveArinV(ALE_MexJet.wsSyteline.FacturaPaso1 Paso) {
            return base.Channel.SaveArinV(Paso);
        }
        
        public System.Threading.Tasks.Task<string> SaveArinVAsync(ALE_MexJet.wsSyteline.FacturaPaso1 Paso) {
            return base.Channel.SaveArinVAsync(Paso);
        }
        
        public string SaveArinVD(ALE_MexJet.wsSyteline.FacturaPaso2 Paso) {
            return base.Channel.SaveArinVD(Paso);
        }
        
        public System.Threading.Tasks.Task<string> SaveArinVDAsync(ALE_MexJet.wsSyteline.FacturaPaso2 Paso) {
            return base.Channel.SaveArinVDAsync(Paso);
        }
        
        public string SaveConceptoFacFinanciera(ALE_MexJet.wsSyteline.FacturaPaso3 Paso) {
            return base.Channel.SaveConceptoFacFinanciera(Paso);
        }
        
        public System.Threading.Tasks.Task<string> SaveConceptoFacFinancieraAsync(ALE_MexJet.wsSyteline.FacturaPaso3 Paso) {
            return base.Channel.SaveConceptoFacFinancieraAsync(Paso);
        }
        
        public System.Data.DataSet GetEstadoCuentaFacturacionMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaFacturacionMXN(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaFacturacionMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaFacturacionMXNAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Data.DataSet GetEstadoCuentaFacturacionDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaFacturacionDLLS(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaFacturacionDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaFacturacionDLLSAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Data.DataSet GetEstadoCuentaResumenNoAcumuladoDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenNoAcumuladoDLLS(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenNoAcumuladoDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenNoAcumuladoDLLSAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Data.DataSet GetEstadoCuentaResumenNoAcumuladoMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenNoAcumuladoMXN(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenNoAcumuladoMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenNoAcumuladoMXNAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Data.DataSet GetEstadoCuentaResumenAcumuladoDLLS(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenAcumuladoDLLS(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenAcumuladoDLLSAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenAcumuladoDLLSAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Data.DataSet GetEstadoCuentaResumenAcumuladoMXN(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenAcumuladoMXN(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEstadoCuentaResumenAcumuladoMXNAsync(string sClaveCliente, System.DateTime dtfechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetEstadoCuentaResumenAcumuladoMXNAsync(sClaveCliente, dtfechaInicio, dtFechaFin);
        }
        
        public string ValidaEstatusCancelacionFactura(string sNumFactura) {
            return base.Channel.ValidaEstatusCancelacionFactura(sNumFactura);
        }
        
        public System.Threading.Tasks.Task<string> ValidaEstatusCancelacionFacturaAsync(string sNumFactura) {
            return base.Channel.ValidaEstatusCancelacionFacturaAsync(sNumFactura);
        }
        
        public System.Data.DataSet GetMovimientosAnterioresEdoCuenta(string sClaveCliente, System.DateTime dtFechaFin) {
            return base.Channel.GetMovimientosAnterioresEdoCuenta(sClaveCliente, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMovimientosAnterioresEdoCuentaAsync(string sClaveCliente, System.DateTime dtFechaFin) {
            return base.Channel.GetMovimientosAnterioresEdoCuentaAsync(sClaveCliente, dtFechaFin);
        }
        
        public string RecuperaTipoCambio() {
            return base.Channel.RecuperaTipoCambio();
        }
        
        public System.Threading.Tasks.Task<string> RecuperaTipoCambioAsync() {
            return base.Channel.RecuperaTipoCambioAsync();
        }
        
        public string RecuperaTipoCambioFecha(System.DateTime Fecha) {
            return base.Channel.RecuperaTipoCambioFecha(Fecha);
        }
        
        public System.Threading.Tasks.Task<string> RecuperaTipoCambioFechaAsync(System.DateTime Fecha) {
            return base.Channel.RecuperaTipoCambioFechaAsync(Fecha);
        }
        
        public string GetFacturasTabulado(string sTiposFactura, System.DateTime dtFechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetFacturasTabulado(sTiposFactura, dtFechaInicio, dtFechaFin);
        }
        
        public System.Threading.Tasks.Task<string> GetFacturasTabuladoAsync(string sTiposFactura, System.DateTime dtFechaInicio, System.DateTime dtFechaFin) {
            return base.Channel.GetFacturasTabuladoAsync(sTiposFactura, dtFechaInicio, dtFechaFin);
        }
        
        public string GeneraSolicitudVuelo(string sClaveContrato, string sNombreContacto, string sCorreoContacto, int iIdMotivo, int iOrigen, string sMatricula, int iIdTipoEquipo, string sNotasVuelo) {
            return base.Channel.GeneraSolicitudVuelo(sClaveContrato, sNombreContacto, sCorreoContacto, iIdMotivo, iOrigen, sMatricula, iIdTipoEquipo, sNotasVuelo);
        }
        
        public System.Threading.Tasks.Task<string> GeneraSolicitudVueloAsync(string sClaveContrato, string sNombreContacto, string sCorreoContacto, int iIdMotivo, int iOrigen, string sMatricula, int iIdTipoEquipo, string sNotasVuelo) {
            return base.Channel.GeneraSolicitudVueloAsync(sClaveContrato, sNombreContacto, sCorreoContacto, iIdMotivo, iOrigen, sMatricula, iIdTipoEquipo, sNotasVuelo);
        }
        
        public string GeneraPiernas(int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros) {
            return base.Channel.GeneraPiernas(iIdSolicitud, sAeropuertoOrigen, sAeropuertoDestino, dtFechaVuelo, sHoraVuelo, iPasajeros);
        }
        
        public System.Threading.Tasks.Task<string> GeneraPiernasAsync(int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros) {
            return base.Channel.GeneraPiernasAsync(iIdSolicitud, sAeropuertoOrigen, sAeropuertoDestino, dtFechaVuelo, sHoraVuelo, iPasajeros);
        }
        
        public string CancelaSolicitudVuelo(int iIdSolicitud) {
            return base.Channel.CancelaSolicitudVuelo(iIdSolicitud);
        }
        
        public System.Threading.Tasks.Task<string> CancelaSolicitudVueloAsync(int iIdSolicitud) {
            return base.Channel.CancelaSolicitudVueloAsync(iIdSolicitud);
        }
        
        public string ConsultaSolicitudVuelo(int iIdSolicitud) {
            return base.Channel.ConsultaSolicitudVuelo(iIdSolicitud);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaSolicitudVueloAsync(int iIdSolicitud) {
            return base.Channel.ConsultaSolicitudVueloAsync(iIdSolicitud);
        }
        
        public string EliminaPiernas(int iIdTramo) {
            return base.Channel.EliminaPiernas(iIdTramo);
        }
        
        public System.Threading.Tasks.Task<string> EliminaPiernasAsync(int iIdTramo) {
            return base.Channel.EliminaPiernasAsync(iIdTramo);
        }
        
        public string ActualizaPiernas(int iIdTramo, int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros) {
            return base.Channel.ActualizaPiernas(iIdTramo, iIdSolicitud, sAeropuertoOrigen, sAeropuertoDestino, dtFechaVuelo, sHoraVuelo, iPasajeros);
        }
        
        public System.Threading.Tasks.Task<string> ActualizaPiernasAsync(int iIdTramo, int iIdSolicitud, string sAeropuertoOrigen, string sAeropuertoDestino, System.DateTime dtFechaVuelo, string sHoraVuelo, int iPasajeros) {
            return base.Channel.ActualizaPiernasAsync(iIdTramo, iIdSolicitud, sAeropuertoOrigen, sAeropuertoDestino, dtFechaVuelo, sHoraVuelo, iPasajeros);
        }
        
        public string ActualizaSolicitud(int iIdSolicitud, int iIdTipoEquipo, string sNotasVuelo) {
            return base.Channel.ActualizaSolicitud(iIdSolicitud, iIdTipoEquipo, sNotasVuelo);
        }
        
        public System.Threading.Tasks.Task<string> ActualizaSolicitudAsync(int iIdSolicitud, int iIdTipoEquipo, string sNotasVuelo) {
            return base.Channel.ActualizaSolicitudAsync(iIdSolicitud, iIdTipoEquipo, sNotasVuelo);
        }
        
        public string ConsultaPreferenciasClienteAPP(string sClaveContrato) {
            return base.Channel.ConsultaPreferenciasClienteAPP(sClaveContrato);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaPreferenciasClienteAPPAsync(string sClaveContrato) {
            return base.Channel.ConsultaPreferenciasClienteAPPAsync(sClaveContrato);
        }
        
        public string ConsultaCasosClienteAPP(string sClaveContrato) {
            return base.Channel.ConsultaCasosClienteAPP(sClaveContrato);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaCasosClienteAPPAsync(string sClaveContrato) {
            return base.Channel.ConsultaCasosClienteAPPAsync(sClaveContrato);
        }
        
        public System.Data.DataSet GetInformacionFlightPak(string sQuery, object[] oArrFiltros) {
            return base.Channel.GetInformacionFlightPak(sQuery, oArrFiltros);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetInformacionFlightPakAsync(string sQuery, object[] oArrFiltros) {
            return base.Channel.GetInformacionFlightPakAsync(sQuery, oArrFiltros);
        }
        
        public string GetInformacionVuelosFerrys() {
            return base.Channel.GetInformacionVuelosFerrys();
        }
        
        public System.Threading.Tasks.Task<string> GetInformacionVuelosFerrysAsync() {
            return base.Channel.GetInformacionVuelosFerrysAsync();
        }
        
        public string SetCambiaEstatusFerry(string sCadJson) {
            return base.Channel.SetCambiaEstatusFerry(sCadJson);
        }
        
        public System.Threading.Tasks.Task<string> SetCambiaEstatusFerryAsync(string sCadJson) {
            return base.Channel.SetCambiaEstatusFerryAsync(sCadJson);
        }
        
        public string SetProcesaJSON(string sCad, int iOpcion) {
            return base.Channel.SetProcesaJSON(sCad, iOpcion);
        }
        
        public System.Threading.Tasks.Task<string> SetProcesaJSONAsync(string sCad, int iOpcion) {
            return base.Channel.SetProcesaJSONAsync(sCad, iOpcion);
        }
        
        public string ObtienePromedioVuelo(int iIdGrupoModelo, string sOrigenICAO, string sDestinoICAO) {
            return base.Channel.ObtienePromedioVuelo(iIdGrupoModelo, sOrigenICAO, sDestinoICAO);
        }
        
        public System.Threading.Tasks.Task<string> ObtienePromedioVueloAsync(int iIdGrupoModelo, string sOrigenICAO, string sDestinoICAO) {
            return base.Channel.ObtienePromedioVueloAsync(iIdGrupoModelo, sOrigenICAO, sDestinoICAO);
        }
        
        public System.Data.DataSet ObtieneDatosPilotoPorClave(string sClave) {
            return base.Channel.ObtieneDatosPilotoPorClave(sClave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtieneDatosPilotoPorClaveAsync(string sClave) {
            return base.Channel.ObtieneDatosPilotoPorClaveAsync(sClave);
        }
        
        public string ObtieneEstatusPiloto(string sCorreo) {
            return base.Channel.ObtieneEstatusPiloto(sCorreo);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneEstatusPilotoAsync(string sCorreo) {
            return base.Channel.ObtieneEstatusPilotoAsync(sCorreo);
        }
        
        public string ObtieneVuelosPorPiloto(string sClavePiloto) {
            return base.Channel.ObtieneVuelosPorPiloto(sClavePiloto);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneVuelosPorPilotoAsync(string sClavePiloto) {
            return base.Channel.ObtieneVuelosPorPilotoAsync(sClavePiloto);
        }
        
        public string ObtieneVuelosPorRangoDeFechas(string sFechaInicio, string sFechaFin) {
            return base.Channel.ObtieneVuelosPorRangoDeFechas(sFechaInicio, sFechaFin);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneVuelosPorRangoDeFechasAsync(string sFechaInicio, string sFechaFin) {
            return base.Channel.ObtieneVuelosPorRangoDeFechasAsync(sFechaInicio, sFechaFin);
        }
        
        public System.Data.DataSet ConsultaCuentaConceptoII(string Cuenta) {
            return base.Channel.ConsultaCuentaConceptoII(Cuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultaCuentaConceptoIIAsync(string Cuenta) {
            return base.Channel.ConsultaCuentaConceptoIIAsync(Cuenta);
        }
        
        public System.Data.DataSet ConsultaPais() {
            return base.Channel.ConsultaPais();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultaPaisAsync() {
            return base.Channel.ConsultaPaisAsync();
        }
        
        public System.Data.DataSet ConsultaEstadoPorPais(int iIdPais) {
            return base.Channel.ConsultaEstadoPorPais(iIdPais);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultaEstadoPorPaisAsync(int iIdPais) {
            return base.Channel.ConsultaEstadoPorPaisAsync(iIdPais);
        }
        
        public string GetPreguntasEncuesta() {
            return base.Channel.GetPreguntasEncuesta();
        }
        
        public System.Threading.Tasks.Task<string> GetPreguntasEncuestaAsync() {
            return base.Channel.GetPreguntasEncuestaAsync();
        }
        
        public string SetRecibeLlamadaConmutador(string sCadJson) {
            return base.Channel.SetRecibeLlamadaConmutador(sCadJson);
        }
        
        public System.Threading.Tasks.Task<string> SetRecibeLlamadaConmutadorAsync(string sCadJson) {
            return base.Channel.SetRecibeLlamadaConmutadorAsync(sCadJson);
        }
        
        public string ObtieneEstatusUsuarioCM(string sCorreo, string sPass) {
            return base.Channel.ObtieneEstatusUsuarioCM(sCorreo, sPass);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneEstatusUsuarioCMAsync(string sCorreo, string sPass) {
            return base.Channel.ObtieneEstatusUsuarioCMAsync(sCorreo, sPass);
        }
        
        public string ObtieneMatriculasPorUsuarioCM(string sCorreo) {
            return base.Channel.ObtieneMatriculasPorUsuarioCM(sCorreo);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneMatriculasPorUsuarioCMAsync(string sCorreo) {
            return base.Channel.ObtieneMatriculasPorUsuarioCMAsync(sCorreo);
        }
        
        public string ObtieneWOporMatriculaCM(string sKeyMatricula) {
            return base.Channel.ObtieneWOporMatriculaCM(sKeyMatricula);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneWOporMatriculaCMAsync(string sKeyMatricula) {
            return base.Channel.ObtieneWOporMatriculaCMAsync(sKeyMatricula);
        }
        
        public string ObtieneDetalleWO(string sKeyWO, string sBase) {
            return base.Channel.ObtieneDetalleWO(sKeyWO, sBase);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneDetalleWOAsync(string sKeyWO, string sBase) {
            return base.Channel.ObtieneDetalleWOAsync(sKeyWO, sBase);
        }
        
        public string ObtieneListadoCotizaciones(string sKeyMatricula) {
            return base.Channel.ObtieneListadoCotizaciones(sKeyMatricula);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneListadoCotizacionesAsync(string sKeyMatricula) {
            return base.Channel.ObtieneListadoCotizacionesAsync(sKeyMatricula);
        }
        
        public string ObtieneDetalleCotizaciones(string sKeyWOQ, string sNumeroWO, string sBase) {
            return base.Channel.ObtieneDetalleCotizaciones(sKeyWOQ, sNumeroWO, sBase);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneDetalleCotizacionesAsync(string sKeyWOQ, string sNumeroWO, string sBase) {
            return base.Channel.ObtieneDetalleCotizacionesAsync(sKeyWOQ, sNumeroWO, sBase);
        }
        
        public string ObtieneVuelosSabanaRangoDeFechas(string sFechaInicio, string sFechaFin) {
            return base.Channel.ObtieneVuelosSabanaRangoDeFechas(sFechaInicio, sFechaFin);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneVuelosSabanaRangoDeFechasAsync(string sFechaInicio, string sFechaFin) {
            return base.Channel.ObtieneVuelosSabanaRangoDeFechasAsync(sFechaInicio, sFechaFin);
        }
        
        public string ObtieneEstadoDeCuentaCorridor(string sIdCompania, string sRFC) {
            return base.Channel.ObtieneEstadoDeCuentaCorridor(sIdCompania, sRFC);
        }
        
        public System.Threading.Tasks.Task<string> ObtieneEstadoDeCuentaCorridorAsync(string sIdCompania, string sRFC) {
            return base.Channel.ObtieneEstadoDeCuentaCorridorAsync(sIdCompania, sRFC);
        }
        
        public string EnviaCorreoWorkOrdersCM(string sJSON) {
            return base.Channel.EnviaCorreoWorkOrdersCM(sJSON);
        }
        
        public System.Threading.Tasks.Task<string> EnviaCorreoWorkOrdersCMAsync(string sJSON) {
            return base.Channel.EnviaCorreoWorkOrdersCMAsync(sJSON);
        }
    }
}
